### ISSUE TITLE
Pendientes: AllpaUtils_names

### ISSUE THREAD

**Issue by brianmsm** [healthinnovation/lis#10]
- [x] 1. Falta realizar la documentación de la función: Título, descripción, parámetros, ejemplo.
- [x] 2. La convención para asignar valores a un objeto es "<-" en lugar del signo igual. Cambiarlo.
- [x] 3. Observación: No es común observar nombres de funciones con mayúsculas y minúsculas intercaladas. Considerar renombrar la función.

Realizar los cambios en https://github.com/healthinnovation/lis/tree/allpautils_names

**Comment by brianmsm** [comment]
#5

**Comment by ambarja** [comment]
Excelente @brianmsm  justo acabo de modificar algunas funciones, por cierto he notado algunos mensajes de error con respecto algunas carácteres especiales en las funciones de vulnerabilidad, no me atreví a cambiar el code pero si quitar esos caracteres, quizás más adelante todo se cambie a ingles.
Saludos
