### ISSUE TITLE
Pendientes: import_db

### ISSUE THREAD

**Issue by brianmsm** [healthinnovation/lis#18]
- [x] 1. Observación: No estoy seguro si este sea la manera correcta de solicitar una data. Revisar: [https://r-pkgs.org/data.html](https://r-pkgs.org/data.html)

**Comment by ambarja** [comment]
Me parece que la estructura adecuada del database (**Peru_shp**) debería ser polígonos y no multipoligonos, esto con la finalidad de evitar algunos warnings con algunos geoprocesamientos. 
@renatocava 
```
peru <- import_db('Peru_shp')
```
![obs](https://user-images.githubusercontent.com/23284899/118898518-5abe5c80-b8d2-11eb-85dd-9c90c826da73.png)

Para poder solucinar esta estructura solo agregar el siguiente código :point_down: 
```
new_base <- peru %>% st_cast('POLYGON')
```
![obs2](https://user-images.githubusercontent.com/23284899/118898531-61e56a80-b8d2-11eb-926d-5c05373dbc61.png)

**Comment by ambarja** [comment]
Nuevo dataset para lis, un cambio por `import_db()`
![2021-06-22 18-48-37](https://user-images.githubusercontent.com/23284899/123014092-1881b280-d38b-11eb-8d57-ca840e425f98.gif)
