### ISSUE TITLE
data(Peru) no está funcionando

### ISSUE THREAD

**Issue by brianmsm** [healthinnovation/lis#33]
La importación de datos no parece estar funcionando correctamente:

``` r
library(lis)
data(Peru)
#> Warning in data(Peru): data set 'Peru' not found
```

<sup>Created on 2021-07-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Me parece que el problema está en la siguiente línea:
https://github.com/healthinnovation/lis/blob/f3acb637bf9ecb89b7ae0769893a5d634dd8b9f1/R/data.R#L20

En vez de `NULL` debería indicar `"Peru"`.

**Comment by ambarja** [comment]
Gracias @brianmsm  ahora lo veo

**Comment by brianmsm** [comment]
Por cierto. Podría tal vez agregarse argumentos para que se puedan obtener niveles administrativos automáticamente (departamental, provincial y distrital).
https://rspatialdata.github.io/admin_boundaries.html

**Comment by ambarja** [comment]
Podría ser una alternativa, pero ¿Crees que lo correcto sea un database?, yo creo que en este caso ya serían una función :thinking:

**Comment by brianmsm** [comment]
Cierto, había olvidado que ya no es una función. O lo otro sería 3 datas, o resolver lo del issue https://github.com/healthinnovation/lis/issues/34
