### ISSUE TITLE
Error: LazyData: false

### ISSUE THREAD

**Issue by brianmsm** [healthinnovation/lis#44]
El motivo de los errores en los últimos checking es que se tiene data que supera ciertos requerimientos que nosotros mismos estamos exigiendo en el documento `DESCRIPTION`.

![imagen](https://user-images.githubusercontent.com/28207224/140594707-afb55b6c-2144-47a7-b8a1-81d37259ad1a.png)

Así está actualmente el archivo  `DESCRIPTION`.
![imagen](https://user-images.githubusercontent.com/28207224/140594718-ca822f34-0cee-490c-9893-9e48e2be5996.png)

Cuando el paquete contiene data se recomienda no indicarlo o ponerle false:
![imagen](https://user-images.githubusercontent.com/28207224/140594744-170511a7-f4b9-43b3-b7d6-1ab44175cf5c.png)

De esa manera el error desaparece:
![imagen](https://user-images.githubusercontent.com/28207224/140594756-8be718e3-9692-43b6-9ae4-f4a5cbcce3f7.png)

**Comment by ambarja** [comment]
Excelente @brianmsm  :3
